---
apiVersion: v1
kind: Service
metadata:
  name: topology-scheduler-metrics
  namespace: kube-system
  labels:
    app: topology-scheduler
spec:
  ports:
  - port: 8080
    targetPort: metrics
    name: metrics
  selector:
    app: topology-scheduler
